on: 
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: haskell-actions/setup@v2
        with:
          ghc-version: '9.6.7'
      - name: update
        run: cabal update
      - name: build
        run: cabal build
      - name: test
        run: cabal test 